title: Posting by Hyun
description: Data Science & Algorith with Computer Science
author: DevelopHyun
github: https://github.com/hwkim94
about: Data Science & Algorith with Computer Science
disqus_shortname: Posting by Hyun
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/sky.hwkim"
    - icon: fa-github
      link: "https://github.com/hwkim94"

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: Category
      url: /category/others

url: "https://hwkim94.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
